version: '2.2'
services:
  sesame:
    build: .
    restart: "always"
    stop_grace_period: 1s
    mem_limit: 1G
    memswap_limit: 1G # we don't use swap, but why not
    pids_limit: 10
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    ports:
      - "4280:4280"
    volumes:
      - "./volumes/service/:/app/data/"
