#!/bin/sh
printf "\n"
printf " * News and announcements: https://twitter.com/RuCTFE or https://t.me/RuCTFE\n"
printf " * Site:                   https://ructfe.org\n"
printf " * Chat:                   https://ructfe.slack.com (register at https://ructfe.org/slack)\n"
printf " * Cloud Console:          https://cloud.ructfe.org\n"
printf " * Monitor:                https://monitor.ructfe.org (for oldfags: https://monitor.ructfe.org/board)\n"
printf " * Flags:                  read https://ructfe.org/http-flags, send to http://10.10.10.10/flags\n"
printf "\n"

/bin/echo -ne "\x1b[0m"
