version: "2.2"

services:
  gateway:
    restart: always
    build:
      context: .
      dockerfile: ./docker/gateway/Dockerfile
    tty: true
    volumes:
      - back_data:/var/www/roms
    ports:
      - "15345:15345"
    ulimits:
      nofile:
        soft: 12000
        hard: 12000

  postgres:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - psql_data:/var/lib/postgresql/data
    mem_limit: 3G
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    cpus: 1.75
    pids_limit: 1000

  backend:
    container_name: backend
    build: ./docker/back
    restart: always
    volumes:
      - back_data:/var/prosopagnosia
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
      SVM_STORAGE_PATH: /var/prosopagnosia
    mem_limit: 4G
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    cpus: 2
    pids_limit: 1000

volumes:
  psql_data:
  back_data:
