version: '2.2'
services:
  kleptophobia:
    build: .
    restart: "always"
    stop_grace_period: 1s
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 80
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    ports:
      - "50051:50051"
  postgres:
    image: postgres:13.2-alpine
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 100
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=myusername
