---
- name: create docker conf dir
  file:
    path: /etc/docker
    state: directory

- name: create docker lib dir
  file:
    path: /home/docker-lib/
    state: directory

- name: configure docker dir before install
  copy:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json
    mode: 0755
    owner: root

- name: Install utils
  apt:
    name:
      - apt-transport-https
      - mc
      - vim
      - htop
      - rsync
      - tmux
      - silversearcher-ag
      - docker.io
      - docker-compose
      - zerofree # for making smaller image size
      - virtualbox-guest-utils
    state: latest
    install_recommends: false
    update_cache: yes

- name: Remove Ubuntu MOTD
  file: path='/etc/update-motd.d/{{ item }}' state=absent
  with_items:
    - 50-motd-news
    - 80-esm
    - 80-livepatch
    - 90-updates-available
    - 91-release-upgrade
    - 95-hwe-eol

- name: Copy banner
  copy:
    src: ructfe-banner.txt
    dest: /ructfe-banner.txt
    mode: 0644

- name: Copy MOTD
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: root
  with_items:
    - {src: "00-header", dest: "/etc/update-motd.d/00-header"}
    - {src: "10-help-text", dest: "/etc/update-motd.d/10-help-text"}

