version: '2.2'
services:
  psycho_clinic:

    image: psycho_clinic
    cpus: 1
    mem_limit: 3G
    memswap_limit: 3G
    pids_limit: 8192
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "18323:18323"
    volumes:
      - data:/app/data

    restart: always
          
volumes:
    data: