# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import models.models_pb2 as models__pb2


class KleptophobiaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/models.Kleptophobia/Register',
                request_serializer=models__pb2.RegisterReq.SerializeToString,
                response_deserializer=models__pb2.RegisterRsp.FromString,
                )
        self.GetPublicInfo = channel.unary_unary(
                '/models.Kleptophobia/GetPublicInfo',
                request_serializer=models__pb2.GetByUsernameReq.SerializeToString,
                response_deserializer=models__pb2.GetPublicInfoRsp.FromString,
                )
        self.GetEncryptedFullInfo = channel.unary_unary(
                '/models.Kleptophobia/GetEncryptedFullInfo',
                request_serializer=models__pb2.GetByUsernameReq.SerializeToString,
                response_deserializer=models__pb2.GetEncryptedFullInfoRsp.FromString,
                )
        self.Ping = channel.unary_unary(
                '/models.Kleptophobia/Ping',
                request_serializer=models__pb2.PingBody.SerializeToString,
                response_deserializer=models__pb2.PingBody.FromString,
                )


class KleptophobiaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEncryptedFullInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KleptophobiaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=models__pb2.RegisterReq.FromString,
                    response_serializer=models__pb2.RegisterRsp.SerializeToString,
            ),
            'GetPublicInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicInfo,
                    request_deserializer=models__pb2.GetByUsernameReq.FromString,
                    response_serializer=models__pb2.GetPublicInfoRsp.SerializeToString,
            ),
            'GetEncryptedFullInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEncryptedFullInfo,
                    request_deserializer=models__pb2.GetByUsernameReq.FromString,
                    response_serializer=models__pb2.GetEncryptedFullInfoRsp.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=models__pb2.PingBody.FromString,
                    response_serializer=models__pb2.PingBody.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'models.Kleptophobia', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Kleptophobia(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.Kleptophobia/Register',
            models__pb2.RegisterReq.SerializeToString,
            models__pb2.RegisterRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPublicInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.Kleptophobia/GetPublicInfo',
            models__pb2.GetByUsernameReq.SerializeToString,
            models__pb2.GetPublicInfoRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEncryptedFullInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.Kleptophobia/GetEncryptedFullInfo',
            models__pb2.GetByUsernameReq.SerializeToString,
            models__pb2.GetEncryptedFullInfoRsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/models.Kleptophobia/Ping',
            models__pb2.PingBody.SerializeToString,
            models__pb2.PingBody.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
