import random
import string

drugs = [
	"agomelatine",
	"alprazolam",
	"amisulpride",
	"amitriptyline",
	"aripiprazole",
	"asenapine",
	"benperidol",
	"buspirone",
	"carbamazepine",
	"cariprazine",
	"chlordiazepoxide",
	"chlorpromazine",
	"citalopram",
	"clomethiazole",
	"clomipramine",
	"clozapine",
	"diazepam",
	"diphenhydramine",
	"dosulepin",
	"doxepin",
	"duloxetine",
	"escitalopram",
	"fluoxetine",
	"flupentixol",
	"fluvoxamine",
	"haloperidol",
	"imipramine",
	"isocarboxazid",
	"lamotrigine",
	"levomepromazine",
	"lithium",
	"lofepramine",
	"loprazolam",
	"lorazepam",
	"lormetazepam",
	"lurasidone",
	"melatonin",
	"mianserin",
	"mirtazapine",
	"moclobemide",
	"nitrazepam",
	"nortriptyline",
	"olanzapine",
	"oxazepam",
	"paliperidone",
	"paroxetine",
	"pericyazine",
	"phenelzine",
	"pimozide",
	"pregabalin",
	"prochlorperazine",
	"promazine",
	"promethazine",
	"quetiapine",
	"reboxetine",
	"risperidone",
	"sertraline",
	"sulpiride",
	"temazepam",
	"tranylcypromine",
	"trazodone",
	"trifluoperazine",
	"trimipramine",
	"valproate",
	"venlafaxine",
	"vortioxetine",
	"zolpidem",
	"zopiclone",
	"zuclopenthixol"
]

def get_prescription(s):
	h = 0;
	for c in s:
		if c in string.ascii_letters or c in string.digits:
			h = ((h * 1677) & 0xffffffff) ^ ord(c);
	return drugs[h % len(drugs)]

disorders = [
	"Absence seizure",
	"Abulia",
	"Acute Stress Disorder",
	"Age-related Cognitive Decline",
	"Agoraphobia",
	"Alzheimer's Disease",
	"Anterograde Amnesia",
	"Anxiety Disorder",
	"Asperger's Syndrome",
	"Attention Deficit Disorder",
	"Attention Deficit Hyperactivity Disorder",
	"Autism Spectrum Disorder",
	"Autophagia",
	"Avoidant Personality Disorder",
	"Binge Eating Disorder",
	"Bipolar disorder",
	"Body Dysmorphic Disorder",
	"Borderline intellectual functioning",
	"Borderline Personality Disorder",
	"Breathing-Related Sleep Disorder",
	"Brief Psychotic Disorder",
	"Bruxism",
	"Bulimia Nervosa",
	"Catatonic disorder",
	"Catatonic schizophrenia",
	"Claustrophobia",
	"Cotard delusion",
	"Delusional Disorder",
	"Dependent Personality Disorder",
	"Depersonalization disorder",
	"Depression",
	"Depressive personality disorder",
	"Derealization disorder",
	"Dermotillomania",
	"Desynchronosis",
	"Developmental coordination disorder",
	"Diogenes Syndrome",
	"Disorder of written expression",
	"Dispareunia",
	"Dissocial Personality Disorder",
	"Dissociative Amnesia",
	"Dissociative Fugue",
	"Dissociative Identity Disorder ",
	"Down syndrome",
	"Dyslexia",
	"Dyspareunia",
	"Ekbom's Syndrome",
	"Encopresis",
	"Erotomania",
	"Exhibitionistic Disorder",
	"Expressive language disorder",
	"Factitious Disorder",
	"Fetishistic Disorder",
	"Fregoli delusion",
	"Frotteuristic Disorder",
	"Ganser syndrome",
	"Grandiose delusions",
	"Histrionic Personality Disorder",
	"Primary hypersomnia",
	"Huntington's Disease",
	"Hypoactive sexual desire disorder",
	"Hypochondriasis",
	"Hypomania",
	"Hyperkinetic syndrome",
	"Hysteria",
	"Impulse control disorder",
	"Insomnia",
	"Joubert syndrome",
	"Korsakoff's syndrome",
	"Lacunar amnesia",
	"Language Disorder",
	"Major depressive disorder",
	"Melancholia",
	"Mental Retardation",
	"Misophonia",
	"Morbid jealousy",
	"Munchausen Syndrome",
	"Narcissistic Personality Disorder",
	"Nightmare Disorder",
	"Non Rapid Eye Movement",
	"Obsessive-Compulsive Disorder",
	"Oneirophrenia",
	"Onychophagia",
	"Oppositional Defiant Disorder",
	"Panic attacks",
	"Panic Disorder",
	"Paranoid Personality Disorder",
	"Parkinson's Disease",
	"Passive-aggressive personality disorder",
	"Pathological gambling",
	"Pedophilic Disorder",
	"Perfectionism",
	"Personality disorder",
	"Phonological disorder",
	"Postpartum Depression",
	"Post Traumatic Stress Disorder",
	"Psychoneurotic personality disorder",
	"Pyromania",
	"Reactive Attachment Disorder",
	"Restless Leg Syndrome",
	"Rumination syndrome",
	"Sadistic personality disorder",
	"Schizoaffective Disorder",
	"Schizoid Personality Disorder",
	"Schizophrenia",
	"Sleep Paralysis",
	"Sleep Terror Disorder",
	"Social Anxiety Disorder",
	"Somatization Disorder",
	"Stendhal syndrome",
	"Stereotypic movement disorder",
	"Tardive dyskinesia",
	"Tourettes Syndrome",
	"Transient tic disorder",
	"Transient global amnesia",
	"Transvestic Disorder",
	"Voyeuristic Disorder"
]


def get_diagnosis(name):
	return "Patient: %s\n\nDiagnosis: %s" % (name, random.choice(disorders))
